queue_rules:
  - name: automerge
    queue_conditions:
      - check-success=Deprecation_Messages_and_Coverage (3.9)
      - "#approved-reviews-by>=1"
      - label=automerge
      - label!=on hold
    merge_conditions:
      - check-success=Deprecation_Messages_and_Coverage (3.9)
    merge_method: squash

pull_request_rules:
  - name: backport
    conditions:
      - label=stable backport potential
    actions:
      backport:
        branches:
          - stable/0.3
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
