# This code is part of a Qiskit project.
#
# (C) Copyright IBM 2021, 2024.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: Algorithms Unit Tests

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:
    branches:
      - main
      - 'stable/**'
  schedule:
    # run every day at 1AM
    - cron: '0 1 * * *'

concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  Checks:
    if: github.repository_owner == 'qiskit-community'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    steps:
      - name: Print Concurrency Group
        env:
          CONCURRENCY_GROUP: ${{ github.repository }}-${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}
        run: |
          echo -e "\033[31;1;4mConcurrency Group\033[0m"
          echo -e "$CONCURRENCY_GROUP\n"
        shell: bash
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            setup.py
            requirements.txt
            requirements-dev.txt
      - uses: ./.github/actions/install-main-dependencies
        with:
          os: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}
          qiskit-main: "false"
        if: ${{ !startsWith(github.ref, 'refs/heads/stable') && !startsWith(github.base_ref, 'stable/') }}
      - uses: ./.github/actions/install-algorithms
      - name: Install Dependencies
        run: |
          sudo apt-get -y install pandoc graphviz python3-enchant hunspell-en-us
          pip install pyenchant
          # append to reno config
          echo "earliest_version: 0.1.0" >> releasenotes/config.yaml
        shell: bash
      - run: pip check
        if: ${{ !cancelled() }}
        shell: bash
      - name: Copyright Check
        run: |
          python tools/check_copyright.py -check
        if: ${{ !cancelled() }}
        shell: bash
      - run: make spell
        if: ${{ !cancelled() }}
        shell: bash
      - name: Style Check
        run: |
          make style
        if: ${{ !cancelled() }}
        shell: bash
      - name: Run make html
        run: |
          make clean_sphinx
          make html
          cd docs/_build/html
          mkdir artifacts
          tar -zcvf artifacts/documentation.tar.gz --exclude=./artifacts .
        if: ${{ !cancelled() }}
        shell: bash
      - name: Run upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/_build/html/artifacts/documentation.tar.gz
        if: ${{ !cancelled() }}
      - run: make doctest
        if: ${{ !cancelled() }}
        shell: bash
  Algorithms:
    if: github.repository_owner == 'qiskit-community'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, 3.9, '3.10', 3.11, 3.12]
        include:
          - os: macos-latest
            python-version: 3.8
          - os: macos-latest
            python-version: 3.12
          - os: windows-latest
            python-version: 3.8
          - os: windows-latest
            python-version: 3.12
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            setup.py
            requirements.txt
            requirements-dev.txt
      - uses: ./.github/actions/install-main-dependencies
        with:
          os: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}
          qiskit-main: "false"
        if: ${{ !startsWith(github.ref, 'refs/heads/stable') && !startsWith(github.base_ref, 'stable/') }}
      - uses: ./.github/actions/install-algorithms
      - run: make lint
        shell: bash
      - run: make mypy
        shell: bash
      - name: Algorithms Unit Tests under Python ${{ matrix.python-version }}
        uses: ./.github/actions/run-tests
        with:
          os: ${{ matrix.os }}
          event-name: ${{ github.event_name }}
          run-slow: ${{ contains(github.event.pull_request.labels.*.name, 'run_slow') }}
          python-version: ${{ matrix.python-version }}
        if: ${{ !cancelled() }}
      - name: Deprecation Messages
        run: |
          mkdir ./ci-artifact-data
          python tools/extract_deprecation.py -file out.txt -output ./ci-artifact-data/alg.dep
        shell: bash
      - name: Coverage combine
        run: |
          coverage3 combine
          mv .coverage ./ci-artifact-data/alg.dat
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == 3.8 }}
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.python-version }}
          path: ./ci-artifact-data/*
  Monitor_Qiskit_Main:
    if: github.repository_owner == 'qiskit-community' && (github.ref == 'refs/heads/main' || github.base_ref == 'main')
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, 3.12]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            setup.py
            requirements.txt
            requirements-dev.txt
      - uses: ./.github/actions/install-main-dependencies
        with:
          os: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}
          qiskit-main: "true"
      - uses: ./.github/actions/install-algorithms
      - run: make lint
        shell: bash
      - run: make mypy
        shell: bash
      - name: Algorithms Unit Tests under Python with Qiskit main ${{ matrix.python-version }}
        uses: ./.github/actions/run-tests
        with:
          os: ${{ matrix.os }}
          event-name: ${{ github.event_name }}
          run-slow: ${{ contains(github.event.pull_request.labels.*.name, 'run_slow') }}
          python-version: ${{ matrix.python-version }}
        if: ${{ !cancelled() }}
  Tutorials:
    if: github.repository_owner == 'qiskit-community'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, 3.12]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            setup.py
            requirements.txt
            requirements-dev.txt
      - uses: ./.github/actions/install-main-dependencies
        with:
          os: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}
        if: ${{ !startsWith(github.ref, 'refs/heads/stable') && !startsWith(github.base_ref, 'stable/') }}
      - uses: ./.github/actions/install-algorithms
      - name: Install Dependencies
        run: |
          pip install jupyter qiskit[visualization]
          sudo apt-get install -y pandoc graphviz
          echo "earliest_version: 0.1.0" >> releasenotes/config.yaml
        shell: bash
      - name: Run Qiskit Algorithms Tutorials
        env:
          QISKIT_PARALLEL: False
          QISKIT_DOCS_BUILD_TUTORIALS: 'always'
        run: |
          make html
          cd docs/_build/html
          mkdir artifacts
          tar -zcvf artifacts/tutorials.tar.gz --exclude=./artifacts .
        shell: bash
      - name: Run upload tutorials
        uses: actions/upload-artifact@v4
        with:
          name: tutorials${{ matrix.python-version }}
          path: docs/_build/html/artifacts/tutorials.tar.gz
  Deprecation_Messages_and_Coverage:
    if: github.repository_owner == 'qiskit-community'
    needs: [Checks, Algorithms, Tutorials]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/download-artifact@v4
        with:
          name: ubuntu-latest-3.8
          path: /tmp/u38
      - uses: actions/download-artifact@v4
        with:
          name: ubuntu-latest-3.9
          path: /tmp/u39
      - uses: actions/download-artifact@v4
        with:
          name: ubuntu-latest-3.10
          path: /tmp/u310
      - uses: actions/download-artifact@v4
        with:
          name: ubuntu-latest-3.11
          path: /tmp/u311
      - uses: actions/download-artifact@v4
        with:
          name: ubuntu-latest-3.12
          path: /tmp/u312
      - uses: actions/download-artifact@v4
        with:
          name: macos-latest-3.8
          path: /tmp/m38
      - uses: actions/download-artifact@v4
        with:
          name: macos-latest-3.12
          path: /tmp/m312
      - uses: actions/download-artifact@v4
        with:
          name: windows-latest-3.8
          path: /tmp/w38
      - uses: actions/download-artifact@v4
        with:
          name: windows-latest-3.12
          path: /tmp/w312
      - name: Install Dependencies
        run: pip install -U coverage coveralls diff-cover
        shell: bash
      - name: Combined Deprecation Messages
        run: |
          sort -f -u /tmp/u38/alg.dep /tmp/u39/alg.dep /tmp/u310/alg.dep /tmp/u311/alg.dep /tmp/u312/alg.dep /tmp/m38/alg.dep /tmp/m312/alg.dep /tmp/w38/alg.dep /tmp/w312/alg.dep || true
        shell: bash
      - name: Coverage combine
        run: coverage3 combine /tmp/u38/alg.dat
        shell: bash
      - name: Upload to Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls --service=github
        shell: bash
